var product_list = [
  {
    product_name: "Áo thun xanh mint",
    product_image: "/asset/img/ao-thun1.jpg",
    product_price: "300.000 VNĐ",
    product_id: "001",
    brand_id: "1",
    description: "Hàng Việt Nam dành cho người Việt nam chất lượng cao ",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
  {
    product_name: "Quần jeans đen",
    product_image: "/asset/img/quan-jean1.jpg",
    product_price: "350.000 VNĐ",
    product_id: "002",
    brand_id: "1",
    description: "danh cho nguoi gay",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
  {
    product_name: "Váy JK xanh biển",
    product_image: "/asset/img/vay-jk1.jpg",
    product_price: "200.000 VNĐ",
    product_id: "003",
    brand_id: "2",
    description: "Được may từ vải cotton chất lượng cao",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
  {
    product_name: "Váy Sunflower",
    product_image: "/asset/img/dam-hoa.jpg",
    product_price: "950.000 VNĐ",
    product_id: "004",
    brand_id: "2",
    description: " Váy sịn sò mặc vào là xinh nhé",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
  {
    product_name: "Quần short xám",
    product_image: "/asset/img/quan-short1.jpg",
    product_price: "230.000 VNĐ",
    product_id: "005",
    brand_id: "3",
    description: "Nam nữ đều có thể mặc ",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
  {
    product_name: "Áo blazer nâu",
    product_image: "/asset/img/ao-blazer1.jpg",
    product_price: "500.000 VNĐ",
    product_id: "006",
    brand_id: "3",
    description: "Mặc cùng quần âu và áo sơ mi là hết sảy",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
  {
    product_name: "Áo Vest xanh biển",
    product_image: "/asset/img/ao-vest1.jpg",
    product_price: "1.500.000 VNĐ",
    product_id:"007",
    brand_id:"3",
    description: "Trông bạn sẽ hòa mình vào biển cả nếu mặc chiếc vest này ",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
  {
    product_name: "Quần kaki xanh đen",
    product_image: "/asset/img/quan-kaki1.jpg",
    product_price: "600.000 VNĐ",
    product_id:"008",
    brand_id:"4",
    description: "Sự kết hợp tuyệt vời của màu xanh và màu đen khiến bạn ngon giai hơn",
    create_date: 22/10/2022,
    product_stock: 20,
    hidden : 1,
  },
];

module.exports = (req, res) => {
  res.render("all-product", { product_list });
};
